version: "3.10"

services:
  stocks_products:
    build: ./stocks_products
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./stocks_products/.env
    volumes:
      - ./app/stocks_products/static/:/app/stocks_products/static/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: my_db
    ports:
      - "5445:5444"
    volumes:
      - pgdata:/var/lib/postgres/data

  nginx:
    build: ./nginx
    depends_on:
      - stocks_products
    volumes:
      - ./app/stocks_products/static/:/app/stocks_products/static/
    ports:
      - "8001:80"

volumes:
  pgdata:
